// src/Pages/ErrorPage.tsx
import { Link } from 'react-router-dom'

function ErrorPages() {
  return (
    <div className="w-full mx-auto pt-10 h-screen dark:text-white">
    <div className="text-center">
      <h1 className="text-4xl md:text-6xl font-bold text-gray-800 mb-4 dark:text-white">
        &#128531;Oops! Page not found.
      </h1>
      <p className="text-xl md:text-2xl text-white mb-8">
        Looks like you're lost in space.
      </p>
      <Link to="/"
        className="inline-block bg-blue-500 hover:bg-blue-600 text-white 
        font-bold py-2 px-4 rounded-md transition duration-300"
        >Back to our site 
     </Link>
    </div>
  </div>
  )
}

export default ErrorPages

// src/Pages/ErrorPage.vue
<template>
    <div
      class="flex items-center justify-center bg-[url('../assets/images/login-bg.png')] h-screen bg-cover"
    >
      <div class="text-center">
        <h1 class="text-4xl md:text-6xl font-bold text-gray-800 mb-4">
          &#128531;Oops! Page not found.
        </h1>
        <p class="text-xl md:text-2xl text-white mb-8">
          Looks like you're lost in space.
        </p>
        <router-link
          to="/"
          class="inline-block bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded-md transition duration-300"
          >Back to Landing Page</router-link
        >
      </div>
    </div>
  </template>
  
  <script setup></script>
  
  <style scoped></style>
